import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 50,
  },
  topcontainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toptextcontainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  topiconcontainer: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderColor: Colors.bordercolor,
    borderWidth: 1,
    borderRadius: 10,
  },
  formcontainer: {
    marginTop: 40,
  },
  formcountrypickercontainer: {
    height: 75,
    borderTopRightRadius: 12,
    borderTopLeftRadius: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.bordercolor,
  },
  formcountrypicker: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  countryregion: {
    fontFamily: "popLight",
    fontSize: 10,
    opacity: 0.3,
  },
  country: {
    fontFamily: "popRegular",
    opacity: 1,
  },
  formnumberinput: {
    fontFamily: "popRegular",
    paddingHorizontal: 15,
    height: 65,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    borderTopWidth: 0,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.bordercolor,
  },
  confirmtext: {
    marginTop: 10,
    fontFamily: "popLight",
    fontSize: 10,
    opacity: 0.5,
    maxWidth: "95%",
  },
  Continue: {
    backgroundColor: Colors.maincolor,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    height: 60,
    borderRadius: 10,
  },
  ContinueText: {
    fontFamily: "popMedium",
    fontSize: 12.5,
    color: "white",
  },
  seperator: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
    position: "relative",
  },
  seperatorText: {
    fontSize: 10,
    fontFamily: "popBold",
  },
  beforeSeperator: {
    position: "absolute",
    left: 0,
    backgroundColor: Colors.bordercolor,
    width: "45%",
    height: 1.5,
    opacity: 0.6,
  },
  afterSeperator: {
    position: "absolute",
    right: 0,
    backgroundColor: Colors.bordercolor,
    width: "45%",
    height: 1.5,
    opacity: 0.6,
  },
  ContinueWithSocial: {
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    height: 60,
    borderRadius: 10,
    borderColor: Colors.bordercolor,
    borderWidth: 1,
    flexDirection: "row",
    position: "relative",
  },
  ContinueWithSocialText: {
    fontFamily: "popMedium",
    fontSize: 12.5,
    color: "black",
  },
  ContinueWithSocialIcon: {
    position: "absolute",
    left: 15,
  },
  formName: {
    height: 65,
    borderTopRightRadius: 12,
    borderTopLeftRadius: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.bordercolor,
    paddingHorizontal: 15,
  },
  FormAdress: {
    fontFamily: "popRegular",
    paddingHorizontal: 15,
    height: 65,
    borderTopWidth: 0,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.bordercolor,
  },
  FormPw: {
    fontFamily: "popRegular",
    paddingHorizontal: 15,
    height: 65,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    borderTopWidth: 0,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.bordercolor,
  },
  FormError: {
    color: "red",
    fontFamily: "popMedium",
    fontSize: 11,
    marginBottom: 5,
    marginLeft: 5,
  },
  UploadContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  ImageBtn: {
    backgroundColor: "black",
    width: 80,
    height: 80,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 50,
  },
  ImageText: {
    fontFamily: "popRegular",
    fontSize: 13,
    marginTop: 5,
    opacity: 0.5,
  },
});

export default styles;
